---
- name: Ensure storage directory exists
  file:
    path: "{{ syncthing_storage_path }}"
    state: directory

- name: Ensure config directory exists
  file:
    path: "{{ ansible_env.HOME }}/.config/containers/syncthing"
    state: directory

- name: Create podman-compose.yml
  template:
    src: podman-compose.yml.j2
    dest: "{{ ansible_env.HOME }}/.config/containers/syncthing/podman-compose.yml"

- name: Deploy Syncthing container
  containers.podman.podman_compose:
    project: syncthing
    files: "{{ ansible_env.HOME }}/.config/containers/syncthing/podman-compose.yml"
    state: present
    # Ensures it runs as the current user (rootless)
    rootless: true
