---
- name: Ensure storage directory exists
  file:
    path: "{{ immich_storage_path }}"
    state: directory

- name: Ensure config directory exists
  file:
    path: "{{ ansible_env.HOME }}/.config/containers/immich"
    state: directory

- name: Create podman-compose.yml
  template:
    src: podman-compose.yml.j2
    dest: "{{ ansible_env.HOME }}/.config/containers/immich/podman-compose.yml"

- name: Deploy Immich container
  containers.podman.podman_compose:
    project: immich
    files: "{{ ansible_env.HOME }}/.config/containers/immich/podman-compose.yml"
    state: present
    rootless: true
