---
- name: Deploy Services
  hosts: all
  tasks:
    - name: Deploy Immich role
      ansible.builtin.import_role:
        name: immich
      tags:
        - immich

    - name: Deploy Syncthing role
      ansible.builtin.import_role:
        name: syncthing
      tags:
        - syncthing
